AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::LanguageExtensions
Description: Wishket Frontend AWS infrastructure.
Parameters:
  Project:
    Type: String
    Default: fe
  Environment:
    Type: String
    Description: Specifies the deployment environment for the AWS infrastructure.
    AllowedValues:
      - test
      - dev
      - stage
      - prod
  VpcCidr:
    Type: String
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 10.0.0.0/16
    Description: The CIDR block of the VPC.
  CertificationArn:
    Type: String
    Description: |
      The ARN of the AWS Certificate Manager (ACM) certificate to use for SSL/TLS termination with the CloudFront distribution.
      This should be the ARN of a certificate that covers the domain or subdomain served by CloudFront.
  WebACL:
    Type: String
    Description: ARN of WebACL created in us-east-1
  NestedStackBucket:
    Type: String
    Description: The name of Bucket holding nested stack templates.
  RootDomainName:
    Type: String
    Default: dev.wishdev.net
  MinCapacity:
    Type: Number
    Default: 1
    Description: |
      The minimum number of instances or tasks that will always be running in the Auto Scaling group or ECS service, even when there is no load.
      Set this at least 2 in production.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - Project
          - Environment
          - NestedStackBucket
      - Label:
          default: Network Configuration
        Parameters:
          - VpcCidr
      - Label:
          default: Certificate Configuration
        Parameters:
          - CertificationArn
Resources:

  #==================================================#
  # Network                                          #
  #==================================================#

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: network.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr

  #==================================================#
  # ECS Services                                     #
  #==================================================#

  ServiceCommonStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: service-common.yaml
  AuthService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: service.yaml
      Parameters:
        NetworkStack: !Select [ 1, !Split [ '/', !Ref NetworkStack ] ]
        ServiceCommonStack: !Select [ 1, !Split [ '/', !Ref ServiceCommonStack ] ]
        CertificationArn: !Ref CertificationArn
        RootDomain: !Ref RootDomainName
        Subdomain: auth
        Cpu: 512
        Memory: 1024
        MinCapacity: !Ref MinCapacity
  WebinarService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: service.yaml
      Parameters:
        NetworkStack: !Select [ 1, !Split [ '/', !Ref NetworkStack ] ]
        ServiceCommonStack: !Select [ 1, !Split [ '/', !Ref ServiceCommonStack ] ]
        CertificationArn: !Ref CertificationArn
        RootDomain: !Ref RootDomainName
        Subdomain: webinar
        MinCapacity: !Ref MinCapacity
  YozmService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: service.yaml
      Parameters:
        NetworkStack: !Select [ 1, !Split [ '/', !Ref NetworkStack ] ]
        ServiceCommonStack: !Select [ 1, !Split [ '/', !Ref ServiceCommonStack ] ]
        CertificationArn: !Ref CertificationArn
        RootDomain: !Ref RootDomainName
        Subdomain: yozm
        MinCapacity: !Ref MinCapacity
  CloudLanding:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: service.yaml
      Parameters:
        NetworkStack: !Select [ 1, !Split [ '/', !Ref NetworkStack ] ]
        ServiceCommonStack: !Select [ 1, !Split [ '/', !Ref ServiceCommonStack ] ]
        CertificationArn: !Ref CertificationArn
        RootDomain: !Ref RootDomainName
        Subdomain: cloud-landing
        MinCapacity: !Ref MinCapacity
  CloudMsp:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: service.yaml
      Parameters:
        NetworkStack: !Select [ 1, !Split [ '/', !Ref NetworkStack ] ]
        ServiceCommonStack: !Select [ 1, !Split [ '/', !Ref ServiceCommonStack ] ]
        CertificationArn: !Ref CertificationArn
        RootDomain: !Ref RootDomainName
        Subdomain: cloud
        MinCapacity: !Ref MinCapacity


  #==================================================#
  # CloudWatch                                       #
  #==================================================#

  CloudWatchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: cloudwatch.yaml
      Parameters:
        ServiceCommonStack: !Select [ 1, !Split [ '/', !Ref ServiceCommonStack ] ]
        AuthService: !Select [ 1, !Split [ '/', !Ref AuthService ] ]
        WebinarService: !Select [ 1, !Split [ '/', !Ref WebinarService ] ]