AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::LanguageExtensions
Description: Wishket Frontend AWS infrastructure.
Parameters:
  Project:
    Type: String
    Default: fe
  Environment:
    Type: String
    Description: Specifies the deployment environment for the AWS infrastructure.
    AllowedValues:
      - test
      - dev
      - stage
      - prod
  VpcCidr:
    Type: String
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Default: 10.0.0.0/16
    Description: The CIDR block of the VPC.
  CertificationArn:
    Type: String
    Description: |
      The ARN of the AWS Certificate Manager (ACM) certificate to use for SSL/TLS termination with the CloudFront distribution.
      This should be the ARN of a certificate that covers the domain or subdomain served by CloudFront.
  WebACL:
    Type: String
    Description: ARN of WebACL created in us-east-1
  NestedStackBucket:
    Type: String
    Description: The name of Bucket holding nested stack templates.
  RootDomainName:
    Type: String
    Default: dev.wishdev.net
Mappings:
  EnvironmentToSubdomainSuffix:
    test:
      Suffix: '-test'
    dev:
      Suffix: ''
    stage:
      Suffix: ''
    prod:
      Suffix: ''
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - Project
          - Environment
          - NestedStackBucket
      - Label:
          default: Network Configuration
        Parameters:
          - VpcCidr
      - Label:
          default: Certificate Configuration
        Parameters:
          - CertificationArn
Resources:

  #==================================================#
  # Network                                          #
  #==================================================#

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: network.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr

  #==================================================#
  # ECS Services                                     #
  #==================================================#

  ServiceCommonStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: service-common.yaml
  AuthService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: service.yaml
      Parameters:
        NetworkStack: !Select [ 1, !Split [ '/', !Ref NetworkStack ] ]
        ServiceCommonStack: !Select [ 1, !Split [ '/', !Ref ServiceCommonStack ] ]
        SubdomainSuffix: !FindInMap [ EnvironmentToSubdomainSuffix, !Ref Environment, Suffix ]
        CertificationArn: !Ref CertificationArn
        RootDomain: !Ref RootDomainName
        Subdomain: !Sub
          - auth${SubdomainSuffix}
          - SubdomainSuffix: !FindInMap [ EnvironmentToSubdomainSuffix, !Ref Environment, Suffix ]
        HealthCheckPath: /api/health # customization
        Cpu: 512
        Memory: 1024
  WishketService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: service.yaml
      Parameters:
        NetworkStack: !Select [ 1, !Split [ '/', !Ref NetworkStack ] ]
        ServiceCommonStack: !Select [ 1, !Split [ '/', !Ref ServiceCommonStack ] ]
        SubdomainSuffix: !FindInMap [ EnvironmentToSubdomainSuffix, !Ref Environment, Suffix ]
        CertificationArn: !Ref CertificationArn
        RootDomain: !Ref RootDomainName
        Subdomain: !Sub
          - wishket${SubdomainSuffix}
          - SubdomainSuffix: !FindInMap [ EnvironmentToSubdomainSuffix, !Ref Environment, Suffix ]
  WebinarService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: service.yaml
      Parameters:
        NetworkStack: !Select [ 1, !Split [ '/', !Ref NetworkStack ] ]
        ServiceCommonStack: !Select [ 1, !Split [ '/', !Ref ServiceCommonStack ] ]
        SubdomainSuffix: !FindInMap [ EnvironmentToSubdomainSuffix, !Ref Environment, Suffix ]
        CertificationArn: !Ref CertificationArn
        RootDomain: !Ref RootDomainName
        Subdomain: !Sub
          - webinar${SubdomainSuffix}
          - SubdomainSuffix: !FindInMap [ EnvironmentToSubdomainSuffix, !Ref Environment, Suffix ]
        HealthCheckPath: /api/health # customization



  #==================================================#
  # CloudWatch                                       #
  #==================================================#

  CloudWatchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/${FileName}
        - BucketName: !Ref NestedStackBucket
          FileName: cloudwatch.yaml
      Parameters:
        ServiceCommonStack: !Select [ 1, !Split [ '/', !Ref ServiceCommonStack ] ]
        AuthService: !Select [ 1, !Split [ '/', !Ref AuthService ] ]
        WishketService: !Select [ 1, !Split [ '/', !Ref WishketService ] ]
        WebinarService: !Select [ 1, !Split [ '/', !Ref WebinarService ] ]