AWSTemplateFormatVersion: '2010-09-09'
Description: Template for resources that needs to be deployed in us-east-1 Region.
Parameters:
  DomainName:
    Type: String
    Default: wishdev.net
    Description: Specifies the root domain for whi a wildcard certificate will be issued, covering all direct subdomains. (e.g. *.wishdev.net)
Resources:
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join [ '.', [ '*', !Ref DomainName ] ]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Join [ '.', [ '*', !Ref DomainName ] ]
          ValidationDomain: !Ref DomainName
Outputs:
  CertificateArn:
    Description: The ARN of the SSL certificate issued by AWS Certificate Manager.
    Value: !Ref SSLCertificate
    Export:
      Name: CertificateArn
