name: Deploy to ECS Fargate
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - release
permissions:
  contents: read
  id-token: write # Required to fetch OpenID Connect token.
env:
  ECR_REPOSITORY:
jobs:
  deploy:
    name: Deploy to ECS Fargate with Canary Deployment
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # replace branch name
    environment: ${{ github.ref == 'refs/heads/main' && 'stage' || github.ref == 'refs/heads/release' && 'production' }}
    strategy:
      matrix:
        environment: [ stage  ]
        include:
          - branch: main
            environment: stage
            ecs_service: ${{ vars.ECS_SERVICE_STAGE }}
            if_condition: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        if: ${{ matrix.if_condition }}
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        if: ${{ matrix.if_condition }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ARN }}
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        if: ${{ matrix.if_condition }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        if: ${{ matrix.if_condition }}
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "ECR Registry $ECR_REPOSITORY"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./test-app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Download task definition
        if: ${{ matrix.if_condition }}
        run: |
          echo "Task Definition Family $TASK_DEFINITION_FAMILY"
          aws ecs describe-task-definition \
            --task-definition ${{ env.TASK_DEFINITION_FAMILY }} \
            --query taskDefinition > task-definition.json
