AWSTemplateFormatVersion: '2010-09-09'
Description: Wishket Frontend CloudFront Infrastructure.
Parameters:
  Project:
    Type: String
  Environment:
    Type: String
  CertificateArn:
    Type: String
  AuthService:
    Type: String
Resources:
  #==================================================#
  # Content Distribution Network                     #
  #==================================================#
  # CDN Path pattern
  # cf. https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesPathPattern
  # noinspection YAMLSchemaValidation
  Distribution:
    Type: AWS::CloudFront::Distribution
    #    DependsOn:
    #      - CloudFrontLoggingBucket
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Test distribution for wishket FE.
        Origins:
          - Id: Auth
            DomainName:
              Fn::ImportValue: !Sub ${AuthService}-DNSName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
            OriginCustomHeaders:
              - HeaderName: X-Custom-Header
                HeaderValue: random-value-1234567890
          - Id: Yozm
            DomainName:
              Fn::ImportValue: !Sub ${YozmService}-DNSName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
            OriginCustomHeaders:
              - HeaderName: X-Custom-Header
                HeaderValue: random-value-1234567890
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
        #        Logging:
        #          Bucket: !Ref CloudFrontLoggingBucket
        DefaultCacheBehavior:
          # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-caching-optimized
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: Auth
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
        CacheBehaviors:
          - PathPattern: /auth/*
            TargetOriginId: Auth
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
          - PathPattern: /yozm/*
            TargetOriginId: Yozm
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
  #        Aliases:
  #          - Fn::Sub:
  #              - ${Project}-${Environment}.wishdev.net
  #              - Project: !Ref Project
  #                Environment: !Ref Environment
  #  CloudFrontLoggingBucket:
  #    Type: AWS::S3::Bucket
  #    Properties:
  #      OwnershipControls:
  #        Rules:
  #          - ObjectOwnership: BucketOwnerPreferred