AWSTemplateFormatVersion: '2010-09-09'
Description: Wishket Frontend CloudWatch Infrastructure.
Parameters:
  ServiceCommonStack:
    Type: String
  AuthService:
    Type: String
  YozmService:
    Type: String
  WishketService:
    Type: String
Resources:
  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardBody: !Sub
        - |
          {
            "widgets": [
              {
                "type": "metric",
                "x": 0,
                "y": 0,
                "width": 24,
                "height": 6,
                "properties": {
                  "metrics": [
                    ["AWS/ECS", "CPUUtilization", "ServiceName", "${AuthService}", "ClusterName", "${ClusterName}"],
                    [".", "MemoryUtilization", ".", ".", ".", "."],
                    [".", "CPUUtilization", ".", "${YozmService}", ".", "."],
                    [".", "MemoryUtilization", ".", ".", ".", "."],
                    [".", "CPUUtilization", ".", "${WishketService}", ".", "."],
                    [".", "MemoryUtilization", ".", ".", ".", "."]
                  ],
                  "period": 300,
                  "stat": "Average",
                  "region": "${AWS::Region}",
                  "title": "Services CPU and Memory Utilization"
                }
              },
              {
                "type": "metric",
                "x": 0,
                "y": 7,
                "width": 24,
                "height": 6,
                "properties": {
                  "metrics": [
                    ["AWS/ECS", "RunningTaskCount", "ServiceName", "${AuthService}", "ClusterName", "${ClusterName}"],
                    ["AWS/ECS", "RunningTaskCount", "ServiceName", "${YozmService}", "ClusterName", "${ClusterName}"],
                    ["AWS/ECS", "RunningTaskCount", "ServiceName", "${WishketService}", "ClusterName", "${ClusterName}"]
                  ],
                  "period": 300,
                  "stat": "Average",
                  "region": "${AWS::Region}",
                  "title": "Running Task Count per Service"
                }
              }
            ]
          }
        - ClusterName:
            Fn::ImportValue: !Sub ${ServiceCommonStack}-Cluster
          AuthService:
            Fn::ImportValue: !Sub ${AuthService}-Service
          YozmService:
            Fn::ImportValue: !Sub ${YozmService}-Service
          WishketService:
            Fn::ImportValue: !Sub ${WishketService}-Service